// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gravan-landing/CalorBrasileiro.tsx": () => import("../components/mockups/gravan-landing/CalorBrasileiro.tsx"),
  "./components/mockups/gravan-landing/FolhaBranca.tsx": () => import("../components/mockups/gravan-landing/FolhaBranca.tsx"),
  "./components/mockups/gravan-landing/NoiteEstudio.tsx": () => import("../components/mockups/gravan-landing/NoiteEstudio.tsx")
};
